#!/bin/bash

mp4File=$1

if [ -z "$mp4File" ]
then
    # display error and exit
    echo "aborting... input file not specified"
    exit
fi

# now generate the hls manifest & chunks
ffmpeg -i $1 -start_number 0 -hls_time 10 -hls_list_size 0 -f hls index.m3u8
